/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's source folder.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CornellNotesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// classifier.ts
var CORNELL_CLASS = "cornell-note";
function hasCornellCssClass(frontmatter) {
  if (!frontmatter || typeof frontmatter !== "object")
    return false;
  const fm = frontmatter;
  return matches(fm.cssclasses) || matches(fm.cssclass);
}
function matches(value) {
  if (Array.isArray(value))
    return value.includes(CORNELL_CLASS);
  if (typeof value === "string")
    return value.split(/\s+/).includes(CORNELL_CLASS);
  return false;
}
function classifyBlocks(markdown, frontmatter) {
  var _a;
  if (!hasCornellCssClass(frontmatter))
    return [];
  const lns = splitLines(markdown);
  const kinds = classifyLines(lns);
  const slots = [];
  const lineRangesOf = (from, toExclusive) => {
    const out = [];
    for (let k = from; k < toExclusive; k++) {
      out.push({ from: lns[k].start, to: lns[k].end });
    }
    return out;
  };
  const blockRange = (from, toExclusive) => ({
    from: lns[from].start,
    to: lns[toExclusive - 1].end
  });
  let i = 0;
  let lastCueSlotIdx = -1;
  let lastCueEndLineIdx = -1;
  while (i < lns.length) {
    const kind = kinds[i];
    if (kind.kind === "callout-start" && (kind.calloutType === "cue" || kind.calloutType === "summary")) {
      let j = i + 1;
      while (j < lns.length && kinds[j].kind === "callout-cont")
        j++;
      const role = kind.calloutType;
      const slot = {
        role,
        sourceRange: blockRange(i, j),
        lineRanges: lineRangesOf(i, j),
        content: extractContent(kinds, i, j)
      };
      if (role === "cue") {
        slot.anchorBlockRange = (_a = findAnchorBlock(lns, kinds, j)) != null ? _a : slot.sourceRange;
        if (lastCueSlotIdx >= 0 && allBlankBetween(kinds, lastCueEndLineIdx + 1, i)) {
          slot.invalid = "adjacent-cue";
          slots[lastCueSlotIdx].invalid = "adjacent-cue";
        } else if (j < lns.length && kinds[j].kind === "body" && isLazyContinuation(lns[j].text)) {
          slot.invalid = "lazy-body";
        }
      }
      slots.push(slot);
      if (role === "cue") {
        const cueIdx = slots.length - 1;
        let g = j;
        while (g < lns.length && kinds[g].kind === "blank")
          g++;
        if (g > j) {
          slots.push({
            role: "gap",
            sourceRange: blockRange(j, g),
            lineRanges: lineRangesOf(j, g)
          });
        }
        lastCueSlotIdx = cueIdx;
        lastCueEndLineIdx = j - 1;
        i = g;
      } else {
        i = j;
      }
      continue;
    }
    if (kind.kind === "callout-start" && kind.calloutType === "title") {
      let m2 = i + 1;
      while (m2 < lns.length && kinds[m2].kind === "callout-cont")
        m2++;
      slots.push({
        role: "title",
        sourceRange: blockRange(i, m2),
        lineRanges: lineRangesOf(i, m2),
        content: extractContent(kinds, i, m2)
      });
      let g = m2;
      while (g < lns.length && kinds[g].kind === "blank")
        g++;
      if (g > m2) {
        slots.push({
          role: "gap",
          sourceRange: blockRange(m2, g),
          lineRanges: lineRangesOf(m2, g)
        });
      }
      i = g;
      continue;
    }
    if (kind.kind === "callout-start") {
      let m2 = i + 1;
      while (m2 < lns.length && kinds[m2].kind === "callout-cont")
        m2++;
      slots.push({
        role: "body",
        sourceRange: blockRange(i, m2),
        lineRanges: lineRangesOf(i, m2)
      });
      i = m2;
      continue;
    }
    if (kind.kind === "frontmatter" || kind.kind === "frontmatter-fence") {
      let m2 = i + 1;
      while (m2 < lns.length && (kinds[m2].kind === "frontmatter" || kinds[m2].kind === "frontmatter-fence")) {
        m2++;
      }
      slots.push({
        role: "full",
        sourceRange: blockRange(i, m2),
        lineRanges: lineRangesOf(i, m2)
      });
      i = m2;
      continue;
    }
    if (kind.kind === "heading") {
      slots.push({
        role: "full",
        sourceRange: blockRange(i, i + 1),
        lineRanges: lineRangesOf(i, i + 1),
        isHeading: true
      });
      i++;
      continue;
    }
    if (kind.kind === "horizontal-rule") {
      slots.push({
        role: "full",
        sourceRange: blockRange(i, i + 1),
        lineRanges: lineRangesOf(i, i + 1),
        isHorizontalRule: true
      });
      i++;
      continue;
    }
    if (kind.kind === "blank") {
      let b = i;
      while (b < lns.length && kinds[b].kind === "blank")
        b++;
      const next = b < lns.length ? kinds[b] : null;
      if (next && next.kind === "callout-start" && next.calloutType === "title") {
        slots.push({
          role: "gap",
          sourceRange: blockRange(i, b),
          lineRanges: lineRangesOf(i, b)
        });
        i = b;
        continue;
      }
      i++;
      continue;
    }
    let m = i + 1;
    while (m < lns.length) {
      const km = kinds[m].kind;
      if (km !== "body" && km !== "code-fence" && km !== "code-inside")
        break;
      m++;
    }
    slots.push({
      role: "body",
      sourceRange: blockRange(i, m),
      lineRanges: lineRangesOf(i, m)
    });
    i = m;
  }
  let page = 0;
  let titleSeen = false;
  for (const slot of slots) {
    if (slot.role === "title") {
      page++;
      slot.pageBreak = titleSeen;
      titleSeen = true;
    }
    slot.page = page;
  }
  let cueOrdinal = -1;
  let currentCue = null;
  for (const slot of slots) {
    if (slot.role === "cue") {
      currentCue = ++cueOrdinal;
      slot.cueGroup = currentCue;
    } else if (slot.role === "title" || slot.role === "summary") {
      currentCue = null;
      slot.cueGroup = null;
    } else {
      slot.cueGroup = currentCue;
    }
  }
  const dividing = (slot) => !!slot && (slot.role === "body" || slot.role === "full" && !!slot.isHeading && slot.cueGroup != null);
  for (let s = 0; s < slots.length; s++) {
    if (!dividing(slots[s]))
      continue;
    if (!dividing(slots[s + 1]))
      slots[s].notesEnd = true;
  }
  return slots;
}
function invalidTooltip(reason) {
  switch (reason) {
    case "adjacent-cue":
      return "Cue has no body block before the next cue. Add content below, or merge the cues.";
    case "lazy-body":
      return "This cue's notes are glued to it. Add a blank line between the cue and the text below so the notes move into the notes column.";
  }
}
function reviewBlurInfo(slot) {
  var _a;
  if (slot.role === "summary") {
    return { blur: true, group: `summary:${(_a = slot.page) != null ? _a : 0}` };
  }
  if (slot.role === "cue" && slot.cueGroup != null) {
    return { blur: false, group: `cue:${slot.cueGroup}` };
  }
  if (slot.cueGroup != null && slot.role === "body") {
    return { blur: true, group: `cue:${slot.cueGroup}` };
  }
  return { blur: false, group: null };
}
var ATTR_SLOT = "data-cornell-slot";
var ATTR_CUE_GROUP = "data-cornell-cue-group";
var ATTR_IN_REGION = "data-cornell-in-region";
var ATTR_NOTES_END = "data-cornell-notes-end";
var ATTR_PAGE_BREAK = "data-cornell-page-break";
var ATTR_REVIEW_BLUR = "data-cornell-review-blur";
var ATTR_REVEALED = "data-cornell-revealed";
var ATTR_LINE = "data-cornell-line";
var ATTR_SUMMARY_START = "data-cornell-summary-start";
var ATTR_OVER_LIMIT = "data-cornell-over-limit";
var ATTR_INVALID = "data-cornell-invalid";
function slotAttributes(slot, notesEnd) {
  const review = reviewBlurInfo(slot);
  return {
    [ATTR_SLOT]: slot.isHeading ? "heading" : slot.role,
    [ATTR_IN_REGION]: slot.isHeading && slot.cueGroup != null ? "" : null,
    [ATTR_PAGE_BREAK]: slot.pageBreak ? "" : null,
    [ATTR_CUE_GROUP]: review.group,
    [ATTR_REVIEW_BLUR]: review.blur ? "" : null,
    [ATTR_NOTES_END]: notesEnd ? "" : null
  };
}
var TITLE_MAX_LENGTH = 60;
var TITLE_OVER_LIMIT_TOOLTIP = "Max title limit hit";
function titleExceedsLimit(text, limit = TITLE_MAX_LENGTH) {
  return text.length > limit;
}
function leadsWithTitle(markdown, frontmatter) {
  var _a;
  const slots = classifyBlocks(markdown, frontmatter);
  if (slots.length === 0)
    return false;
  let idx = 0;
  if (slots[0].role === "full" && slots[0].sourceRange.from === 0) {
    const nl = markdown.indexOf("\n");
    const firstLine = nl === -1 ? markdown : markdown.slice(0, nl);
    if (firstLine.trim() === "---")
      idx = 1;
  }
  const lead = slots[idx];
  return (lead == null ? void 0 : lead.role) === "title" && !!((_a = lead.content) == null ? void 0 : _a.trim());
}
function slotForLineRange(markdown, frontmatter, lineStart, lineEnd) {
  const slots = classifyBlocks(markdown, frontmatter);
  if (slots.length === 0)
    return null;
  let line = 0;
  let offset = 0;
  const lineOf = (off) => {
    while (offset < off && offset < markdown.length) {
      if (markdown[offset] === "\n")
        line++;
      offset++;
    }
    return line;
  };
  for (const slot of slots) {
    const sStart = lineOf(slot.sourceRange.from);
    const sEnd = lineOf(Math.max(slot.sourceRange.from, slot.sourceRange.to - 1));
    if (sStart <= lineEnd && sEnd >= lineStart)
      return slot;
  }
  return null;
}
function classifySection(markdown, frontmatter, lineStart, lineEnd) {
  const slot = slotForLineRange(markdown, frontmatter, lineStart, lineEnd);
  if (!slot)
    return null;
  let notesEnd = false;
  if (slot.notesEnd && (slot.role === "body" || slot.isHeading)) {
    notesEnd = lineEnd >= lineIndexOf(markdown, slot.sourceRange.to - 1);
  }
  return { slot, notesEnd };
}
function lineIndexOf(markdown, offset) {
  let line = 0;
  const end = Math.min(offset, markdown.length);
  for (let i = 0; i < end; i++) {
    if (markdown[i] === "\n")
      line++;
  }
  return line;
}
function splitLines(text) {
  const out = [];
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === "\n") {
      let lineText = text.slice(start, i);
      if (lineText.endsWith("\r"))
        lineText = lineText.slice(0, -1);
      out.push({ text: lineText, start, end: i + 1 });
      start = i + 1;
    }
  }
  if (start < text.length) {
    let lineText = text.slice(start);
    if (lineText.endsWith("\r"))
      lineText = lineText.slice(0, -1);
    out.push({ text: lineText, start, end: text.length });
  }
  return out;
}
function classifyLines(lns) {
  const out = [];
  let inFrontmatter = false;
  let frontmatterClosed = false;
  let inCodeFence = false;
  let codeFenceMarker = "";
  for (let i = 0; i < lns.length; i++) {
    const text = lns[i].text;
    if (!frontmatterClosed && i === 0 && text.trim() === "---") {
      inFrontmatter = true;
      out.push({ kind: "frontmatter-fence" });
      continue;
    }
    if (inFrontmatter) {
      if (text.trim() === "---") {
        inFrontmatter = false;
        frontmatterClosed = true;
        out.push({ kind: "frontmatter-fence" });
      } else {
        out.push({ kind: "frontmatter" });
      }
      continue;
    }
    const fenceMatch = text.match(/^\s*(`{3,}|~{3,})/);
    if (inCodeFence) {
      if (fenceMatch && fenceMatch[1][0] === codeFenceMarker[0] && fenceMatch[1].length >= codeFenceMarker.length) {
        inCodeFence = false;
        codeFenceMarker = "";
        out.push({ kind: "code-fence" });
      } else {
        out.push({ kind: "code-inside" });
      }
      continue;
    }
    if (fenceMatch) {
      inCodeFence = true;
      codeFenceMarker = fenceMatch[1];
      out.push({ kind: "code-fence" });
      continue;
    }
    if (text.trim() === "") {
      out.push({ kind: "blank" });
      continue;
    }
    const calloutStart = text.match(/^>\s*\[!(\w[\w-]*)\][+-]?\s*(.*)$/);
    if (calloutStart) {
      out.push({
        kind: "callout-start",
        calloutType: calloutStart[1].toLowerCase(),
        titleText: calloutStart[2].trim()
      });
      continue;
    }
    const calloutCont = text.match(/^>\s?(.*)$/);
    if (calloutCont) {
      const prev = out[out.length - 1];
      if (prev && (prev.kind === "callout-start" || prev.kind === "callout-cont")) {
        out.push({ kind: "callout-cont", bodyText: calloutCont[1] });
        continue;
      }
    }
    const headingMatch = text.match(/^(#+)\s+/);
    if (headingMatch) {
      out.push({ kind: "heading", level: headingMatch[1].length });
      continue;
    }
    if (/^\s*([-*_])(?:\s*\1){2,}\s*$/.test(text)) {
      out.push({ kind: "horizontal-rule" });
      continue;
    }
    out.push({ kind: "body" });
  }
  return out;
}
function isLazyContinuation(text) {
  const t = text.replace(/^\s+/, "");
  if (/^([-*+]|\d+[.)])\s+/.test(t))
    return false;
  if (t.startsWith("|"))
    return false;
  return true;
}
function allBlankBetween(kinds, from, toExclusive) {
  for (let k = from; k < toExclusive; k++) {
    if (kinds[k].kind !== "blank")
      return false;
  }
  return true;
}
function extractContent(kinds, i, j) {
  const startKind = kinds[i];
  if (startKind.kind !== "callout-start")
    return "";
  let content = startKind.titleText;
  for (let k = i + 1; k < j; k++) {
    const kk = kinds[k];
    if (kk.kind === "callout-cont" && kk.bodyText.trim()) {
      if (content)
        content += "\n";
      content += kk.bodyText;
    }
  }
  return content;
}
function findAnchorBlock(lns, kinds, start) {
  let k = start;
  while (k < lns.length && kinds[k].kind === "blank")
    k++;
  if (k >= lns.length)
    return null;
  if (kinds[k].kind === "callout-start") {
    let nextStart = k + 1;
    while (nextStart < lns.length && kinds[nextStart].kind === "callout-cont") {
      nextStart++;
    }
    return findAnchorBlock(lns, kinds, nextStart);
  }
  const firstLine = lns[k];
  let m = k + 1;
  while (m < lns.length && kinds[m].kind !== "blank" && kinds[m].kind !== "callout-start") {
    m++;
  }
  const lastLine = lns[m - 1];
  return { from: firstLine.start, to: lastLine.end };
}

// pdfExport.ts
var import_obsidian = require("obsidian");

// exportMap.ts
function stripFrontmatter(source) {
  const m = source.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/);
  return m ? source.slice(m[0].length) : source;
}
function buildPrintableMarkdown(source, basename) {
  const body = stripFrontmatter(source);
  const safeTitle = basename.replace(/[\r\n]+/g, " ").trim();
  return `> [!title] ${safeTitle}

${body}`;
}
function classifyPrintable(markdown) {
  return classifyBlocks(markdown, { cssclasses: ["cornell-note"] });
}
function anchorKind(shape) {
  if (shape.kind === "callout") {
    const t = shape.calloutType;
    return t === "cue" || t === "summary" || t === "title" ? t : null;
  }
  if (shape.kind === "heading")
    return "heading";
  if (shape.kind === "hr")
    return "hr";
  return null;
}
function slotMatches(slot, anchor) {
  switch (anchor) {
    case "cue":
    case "summary":
    case "title":
      return slot.role === anchor;
    case "heading":
      return slot.role === "full" && !!slot.isHeading;
    case "hr":
      return slot.role === "full" && !!slot.isHorizontalRule;
  }
}
function mapSlotsToBlocks(slots, shapes) {
  const assigned = [];
  let j = 0;
  let fallbackActive = false;
  for (const shape of shapes) {
    if (shape.kind === "chrome") {
      assigned.push({ role: null, inRegion: false });
      continue;
    }
    const anchor = anchorKind(shape);
    if (anchor) {
      let k = j;
      while (k < slots.length && !slotMatches(slots[k], anchor))
        k++;
      if (k < slots.length) {
        const slot = slots[k];
        j = k + 1;
        if (anchor === "hr") {
          assigned.push({ role: null, inRegion: false });
        } else if (anchor === "heading") {
          assigned.push({ role: "heading", inRegion: slot.cueGroup != null });
        } else {
          assigned.push({ role: anchor, inRegion: false });
        }
      } else if (anchor === "hr") {
        assigned.push({ role: null, inRegion: false });
      } else if (anchor === "heading") {
        assigned.push({ role: "heading", inRegion: fallbackActive });
      } else {
        assigned.push({ role: anchor, inRegion: false });
      }
    } else {
      assigned.push({ role: "body", inRegion: false });
    }
    const role = assigned[assigned.length - 1].role;
    if (role === "cue")
      fallbackActive = true;
    else if (role === "title" || role === "summary")
      fallbackActive = false;
  }
  const dividing = (i) => {
    const a = assigned[i];
    return !!a && (a.role === "body" || a.role === "heading" && a.inRegion);
  };
  return assigned.map((a, i) => ({
    ...a,
    notesEnd: dividing(i) && !dividing(i + 1)
  }));
}

// pdfExport.ts
var HEADING_SELECTOR = "h1, h2, h3, h4, h5, h6";
function blockShape(child) {
  const hasCallout = (type) => child.matches(`.callout[data-callout="${type}"]`) || !!child.querySelector(`.callout[data-callout="${type}"]`);
  for (const type of ["cue", "summary", "title"]) {
    if (hasCallout(type))
      return { kind: "callout", calloutType: type };
  }
  if (child.matches(".callout") || child.querySelector(".callout")) {
    return { kind: "callout" };
  }
  if (child.matches(".mod-header, .metadata-container, .frontmatter") || child.querySelector(".metadata-container, .frontmatter, .inline-title")) {
    return { kind: "chrome" };
  }
  if (child.matches(HEADING_SELECTOR) || child.querySelector(HEADING_SELECTOR)) {
    return { kind: "heading" };
  }
  if (child.matches("hr") || child.querySelector(":scope > hr")) {
    return { kind: "hr" };
  }
  return { kind: "other" };
}
function applyAssignment(child, a) {
  child.removeAttribute(ATTR_REVIEW_BLUR);
  if (a.role === null) {
    child.removeAttribute(ATTR_SLOT);
    child.removeAttribute(ATTR_IN_REGION);
    child.removeAttribute(ATTR_NOTES_END);
    return;
  }
  child.setAttribute(ATTR_SLOT, a.role);
  child.toggleAttribute(ATTR_IN_REGION, a.role === "heading" && a.inRegion);
  child.toggleAttribute(ATTR_NOTES_END, a.notesEnd);
}
function stampGridFromSlots(host, slots) {
  const kids = Array.from(host.children).filter(
    (c) => c.instanceOf(HTMLElement)
  );
  const assignments = mapSlotsToBlocks(slots, kids.map(blockShape));
  kids.forEach((child, i) => applyAssignment(child, assignments[i]));
}
function stampExportHost(host) {
  const kids = Array.from(host.children).filter(
    (c) => c.instanceOf(HTMLElement)
  );
  const assignments = mapSlotsToBlocks([], kids.map(blockShape));
  kids.forEach((child, i) => applyAssignment(child, assignments[i]));
}
var HOLDER_CLASS = "cornell-pdf-export-holder";
var A4_PRINT_OPTIONS = {
  printBackground: true,
  pageSize: { width: 210 / 25.4, height: 297 / 25.4 }
};
function resolvePdfOutputPath(file) {
  const dir = file.parent && !file.parent.isRoot() ? `${file.parent.path}/` : "";
  return (0, import_obsidian.normalizePath)(`${dir}${file.basename}.pdf`);
}
function resolveCombinedOutputPath(folderPath, name) {
  const base = name.replace(/[\r\n]+/g, " ").trim() || "Cornell Notes";
  const fileName = base.toLowerCase().endsWith(".pdf") ? base : `${base}.pdf`;
  const dir = folderPath && folderPath !== "/" ? `${folderPath}/` : "";
  return (0, import_obsidian.normalizePath)(`${dir}${fileName}`);
}
function descendantMarkdownFiles(folder) {
  const out = [];
  const walk = (f) => {
    for (const child of f.children) {
      if (child instanceof import_obsidian.TFolder) {
        walk(child);
      } else if (child instanceof import_obsidian.TFile && child.extension === "md") {
        out.push(child);
      }
    }
  };
  walk(folder);
  return out;
}
function collectCornellNotes(files, getFrontmatter) {
  return files.filter((file) => hasCornellCssClass(getFrontmatter(file)));
}
function collectAppStyles(doc) {
  const css = [];
  Array.from(doc.styleSheets).forEach((sheet) => {
    var _a;
    try {
      Array.from((_a = sheet.cssRules) != null ? _a : []).forEach((rule) => css.push(rule.cssText));
    } catch (e) {
    }
  });
  return css.join("\n");
}
function buildExportBody(gridHtml) {
  return `<div class="${HOLDER_CLASS} cornell-note markdown-preview-view markdown-rendered">${gridHtml}</div>`;
}
function buildCombinedExportBody(gridHtmls) {
  return `<div class="${HOLDER_CLASS} cornell-note markdown-preview-view markdown-rendered">${gridHtmls.join(
    ""
  )}</div>`;
}
var PRINT_PATCH = `
.${HOLDER_CLASS}, .${HOLDER_CLASS} * {
  content-visibility: visible !important;
  contain: none !important;
}
html, body { height: auto !important; overflow: visible !important; }
.print, .${HOLDER_CLASS} { display: block !important; }
@media print {
  html, body { height: auto !important; overflow: visible !important; }
  .print, .${HOLDER_CLASS} { display: block !important; }
  .${HOLDER_CLASS} { min-height: 0 !important; }
}
`;
function buildSetupScript(bodyHtml, bodyClass) {
  return `
    document.body.className = ${JSON.stringify(bodyClass)};
    document.body.innerHTML = decodeURIComponent("${encodeURIComponent(bodyHtml)}");
    true;
  `;
}
async function renderCornellExportGrid(app, file) {
  const doc = activeDocument;
  const win = activeWindow;
  const source = await app.vault.cachedRead(file);
  const markdown = buildPrintableMarkdown(source, file.basename);
  const renderHost = doc.body.createDiv({
    cls: `${HOLDER_CLASS} cornell-note`
  });
  const grid = renderHost.createDiv({ cls: "cornell-grid markdown-rendered" });
  const component = new import_obsidian.Component();
  component.load();
  const dispose = () => {
    component.unload();
    renderHost.remove();
  };
  try {
    await import_obsidian.MarkdownRenderer.render(app, markdown, grid, file.path, component);
    stampGridFromSlots(grid, classifyPrintable(markdown));
    await new Promise((resolve) => win.setTimeout(resolve, 150));
    return { grid, dispose };
  } catch (e) {
    dispose();
    throw e;
  }
}
function bodyClassForExport(doc) {
  return [
    ...Array.from(doc.body.classList).filter((c) => c !== "theme-dark"),
    "theme-light",
    "cornell-printing"
  ].join(" ");
}
async function prepareExportWebview(host, options) {
  const doc = activeDocument;
  const win = activeWindow;
  const webview = doc.createElement("webview");
  webview.classList.add("cornell-pdf-capture");
  webview.setAttribute("src", "app://obsidian.md/help.html");
  webview.setAttribute("nodeintegration", "true");
  webview.setCssStyles({ width: "100%", height: "100%", border: "0" });
  host.appendChild(webview);
  await new Promise((resolve, reject) => {
    const timer = win.setTimeout(
      () => reject(new Error("webview load timed out")),
      15e3
    );
    webview.addEventListener(
      "dom-ready",
      () => {
        void (async () => {
          try {
            win.clearTimeout(timer);
            await webview.insertCSS(collectAppStyles(doc));
            await webview.executeJavaScript(
              buildSetupScript(options.bodyHtml, options.bodyClass)
            );
            await webview.insertCSS(PRINT_PATCH);
            resolve();
          } catch (e) {
            reject(e instanceof Error ? e : new Error(String(e)));
          }
        })();
      },
      { once: true }
    );
  });
  await new Promise((resolve) => win.setTimeout(resolve, 250));
  const baseWidth = webview.style.width || "100%";
  webview.setCssStyles({ width: "99%" });
  await new Promise((resolve) => win.setTimeout(resolve, 30));
  webview.setCssStyles({ width: baseWidth });
  await new Promise((resolve) => win.setTimeout(resolve, 30));
  return webview;
}
async function printPreparedWebview(webview) {
  const win = activeWindow;
  const toggle = (on) => webview.executeJavaScript(
    `(function(){var h=document.querySelector(${JSON.stringify(
      `.${HOLDER_CLASS}`
    )});if(h){h.classList.${on ? "add" : "remove"}("print");}return true;})()`
  );
  await toggle(true);
  await new Promise((resolve) => win.setTimeout(resolve, 50));
  try {
    const data = await webview.printToPDF(A4_PRINT_OPTIONS);
    const out = new ArrayBuffer(data.byteLength);
    new Uint8Array(out).set(data);
    return out;
  } finally {
    await toggle(false);
  }
}

// pdfExportModal.ts
var import_obsidian2 = require("obsidian");
var CornellPdfExportModal = class extends import_obsidian2.Modal {
  constructor(plugin, files) {
    super(plugin.app);
    this.outputMode = "separate";
    /** Combined-mode output target — a file name (extension optional) and a vault
     *  folder path ("/" = root). Only used when `outputMode === "combined"`. */
    this.combinedName = "Cornell Notes";
    this.combinedFolder = "/";
    /** The combined-only inputs row, shown/hidden with the output mode. */
    this.combinedRow = null;
    this.renderBtn = null;
    this.exportBtn = null;
    this.previewEl = null;
    /** Disposers for the grids currently mounted in the preview, cleared on
     *  re-render and on close so render components are always unloaded. */
    this.previewDisposers = [];
    /** Body-level on-screen host that backs the capture <webview> during export.
     *  Held so it can be torn down if the modal closes mid-export. */
    this.captureHost = null;
    this.exporting = false;
    this.plugin = plugin;
    this.files = files;
    this.checked = new Set(files);
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("cornell-pdf-export-modal");
    this.titleEl.setText(
      this.files.length === 1 ? "Export note to PDF" : "Export notes to PDF"
    );
    if (this.files.length > 1) {
      const controls = contentEl.createDiv({
        cls: "cornell-pdf-export-controls"
      });
      const modeLabel = controls.createEl("label", { text: "Output" });
      modeLabel.addClass("cornell-pdf-export-label");
      const modeSelect = modeLabel.createEl("select");
      modeSelect.createEl("option", {
        text: "One PDF per note",
        value: "separate"
      });
      modeSelect.createEl("option", { text: "Combined PDF", value: "combined" });
      modeSelect.value = this.outputMode;
      modeSelect.addEventListener("change", () => {
        var _a;
        this.outputMode = modeSelect.value;
        (_a = this.combinedRow) == null ? void 0 : _a.classList.toggle(
          "cornell-pdf-hidden",
          this.outputMode !== "combined"
        );
      });
      this.combinedRow = contentEl.createDiv({ cls: "cornell-pdf-combined-row" });
      const nameLabel = this.combinedRow.createEl("label", { text: "File name" });
      nameLabel.addClass("cornell-pdf-export-label");
      const nameInput = nameLabel.createEl("input", { type: "text" });
      nameInput.value = this.combinedName;
      nameInput.addEventListener("input", () => {
        this.combinedName = nameInput.value;
      });
      const folderLabel = this.combinedRow.createEl("label", { text: "Folder" });
      folderLabel.addClass("cornell-pdf-export-label");
      const folderSelect = folderLabel.createEl("select");
      this.folderOptions().forEach((opt) => {
        folderSelect.createEl("option", { text: opt.label, value: opt.value });
      });
      folderSelect.value = this.combinedFolder;
      folderSelect.addEventListener("change", () => {
        this.combinedFolder = folderSelect.value;
      });
      this.combinedRow.classList.toggle(
        "cornell-pdf-hidden",
        this.outputMode !== "combined"
      );
    }
    const selHeader = contentEl.createDiv({
      cls: "cornell-pdf-selection-header"
    });
    selHeader.createEl("span", {
      cls: "cornell-pdf-selection-title",
      text: `${this.files.length} cornell note${this.files.length === 1 ? "" : "s"}`
    });
    const selActions = selHeader.createDiv({
      cls: "cornell-pdf-selection-actions"
    });
    new import_obsidian2.ButtonComponent(selActions).setButtonText("Select all").onClick(() => this.setAllChecked(true));
    new import_obsidian2.ButtonComponent(selActions).setButtonText("Select none").onClick(() => this.setAllChecked(false));
    const list = contentEl.createDiv({ cls: "cornell-pdf-note-list" });
    this.files.forEach((file) => {
      const item = list.createEl("label", { cls: "cornell-pdf-note-item" });
      const box = item.createEl("input", { type: "checkbox" });
      box.checked = this.checked.has(file);
      box.dataset.path = file.path;
      box.addEventListener("change", () => {
        if (box.checked)
          this.checked.add(file);
        else
          this.checked.delete(file);
        this.updateButtons();
      });
      item.createEl("span", {
        cls: "cornell-pdf-note-name",
        text: file.basename
      });
      if (file.parent && !file.parent.isRoot()) {
        item.createEl("span", {
          cls: "cornell-pdf-note-path",
          text: file.parent.path
        });
      }
    });
    const renderRow = contentEl.createDiv({ cls: "cornell-pdf-render-row" });
    this.renderBtn = new import_obsidian2.ButtonComponent(renderRow).setButtonText("Render preview").onClick(() => void this.renderPreview());
    this.previewEl = contentEl.createDiv({ cls: "cornell-pdf-export-preview" });
    this.previewEl.createDiv({
      cls: "cornell-pdf-export-status",
      text: "Select notes and click Render preview to see them here."
    });
    const buttons = contentEl.createDiv({ cls: "cornell-pdf-export-buttons" });
    new import_obsidian2.ButtonComponent(buttons).setButtonText("Cancel").onClick(() => this.close());
    this.exportBtn = new import_obsidian2.ButtonComponent(buttons).setButtonText("Export").setCta().onClick(() => void this.runExport());
    this.updateButtons();
  }
  /** Tick or untick every note and sync the checkboxes + buttons. */
  setAllChecked(on) {
    this.checked.clear();
    if (on)
      this.files.forEach((f) => this.checked.add(f));
    this.contentEl.querySelectorAll(".cornell-pdf-note-item input").forEach((box) => {
      box.checked = on;
    });
    this.updateButtons();
  }
  /** The notes currently ticked, in the original (scope) order. */
  selectedFiles() {
    return this.files.filter((f) => this.checked.has(f));
  }
  /** Enable Render / Export only when at least one note is checked and no export
   *  is in flight. */
  updateButtons() {
    var _a, _b;
    const has = this.selectedFiles().length > 0;
    (_a = this.renderBtn) == null ? void 0 : _a.setDisabled(this.exporting || !has);
    (_b = this.exportBtn) == null ? void 0 : _b.setDisabled(this.exporting || !has);
  }
  /** Unload every preview render component and clear the preview surface. */
  disposePreview() {
    var _a;
    this.previewDisposers.forEach((d) => d());
    this.previewDisposers = [];
    (_a = this.previewEl) == null ? void 0 : _a.empty();
  }
  /** Render each checked note as native in-app DOM, stacked in the scrollable
   *  preview. A note that fails to render is reported inline; the rest still
   *  render. Re-rendering disposes the previous preview first. */
  async renderPreview() {
    if (this.exporting || !this.previewEl)
      return;
    const files = this.selectedFiles();
    if (files.length === 0) {
      new import_obsidian2.Notice("Select at least one cornell note to preview.");
      return;
    }
    this.disposePreview();
    const status = this.previewEl.createDiv({
      cls: "cornell-pdf-export-status",
      text: "Rendering preview\u2026"
    });
    for (const file of files) {
      try {
        const { grid, dispose } = await renderCornellExportGrid(this.app, file);
        this.previewDisposers.push(dispose);
        const sheet = this.previewEl.createDiv({
          cls: "cornell-pdf-preview-sheet cornell-note"
        });
        sheet.appendChild(grid);
      } catch (e) {
        this.previewEl.createDiv({
          cls: "cornell-pdf-export-status cornell-pdf-export-error",
          text: `Could not render "${file.basename}": ${String(e)}`
        });
      }
    }
    status.remove();
  }
  /** Vault folders for the combined-mode target dropdown — root first, then every
   *  folder by path. Root is shown as "(vault root)" and stored as "/". */
  folderOptions() {
    const byPath = /* @__PURE__ */ new Map([["/", "(vault root)"]]);
    this.app.vault.getAllLoadedFiles().forEach((f) => {
      if (f instanceof import_obsidian2.TFolder && !f.isRoot())
        byPath.set(f.path, f.path);
    });
    return Array.from(byPath, ([value, label]) => ({ value, label })).sort(
      (a, b) => a.label.localeCompare(b.label)
    );
  }
  /** Export the checked notes, branching on the output mode, with one shared
   *  on-screen capture host. Tears the host down and reports a summary either
   *  way; a clean run closes the modal, any failure keeps it open for retry. */
  async runExport() {
    var _a, _b;
    if (this.exporting)
      return;
    const files = this.selectedFiles();
    if (files.length === 0) {
      new import_obsidian2.Notice("Select at least one cornell note to export.");
      return;
    }
    this.exporting = true;
    this.updateButtons();
    (_a = this.exportBtn) == null ? void 0 : _a.setButtonText("Exporting\u2026");
    const host = activeDocument.body.createDiv({ cls: "cornell-pdf-export-host" });
    this.captureHost = host;
    this.positionCaptureHost();
    const bodyClass = bodyClassForExport(activeDocument);
    let summary;
    try {
      summary = this.outputMode === "combined" ? await this.exportCombined(files, host, bodyClass) : await this.exportSeparate(files, host, bodyClass);
    } finally {
      (_b = this.captureHost) == null ? void 0 : _b.remove();
      this.captureHost = null;
      this.exporting = false;
    }
    this.reportExport(files.length, summary);
  }
  /** One PDF per note, beside each source, captured one at a time through the
   *  shared host. A note that fails is skipped; the rest still export. */
  async exportSeparate(files, host, bodyClass) {
    const failed = [];
    let exported = 0;
    for (const file of files) {
      let webview = null;
      try {
        const { grid, dispose } = await renderCornellExportGrid(this.app, file);
        const gridHtml = grid.outerHTML;
        dispose();
        webview = await prepareExportWebview(host, {
          bodyHtml: buildExportBody(gridHtml),
          bodyClass
        });
        const bytes = await printPreparedWebview(webview);
        await this.app.vault.adapter.writeBinary(
          resolvePdfOutputPath(file),
          bytes
        );
        exported++;
      } catch (e) {
        console.error(`Cornell PDF export failed for ${file.path}`, e);
        failed.push(file.basename);
      } finally {
        webview == null ? void 0 : webview.remove();
      }
    }
    return { exported, failed, wrote: exported > 0 };
  }
  /** All selected notes merged into one PDF (each note on a fresh page), written
   *  to the combined name + folder. Notes that fail to render are skipped; the
   *  combined file is still written from the rest. `exported` is the number of
   *  notes included in the file. */
  async exportCombined(files, host, bodyClass) {
    const failed = [];
    const gridHtmls = [];
    for (const file of files) {
      try {
        const { grid, dispose } = await renderCornellExportGrid(this.app, file);
        gridHtmls.push(grid.outerHTML);
        dispose();
      } catch (e) {
        console.error(`Cornell PDF render failed for ${file.path}`, e);
        failed.push(file.basename);
      }
    }
    if (gridHtmls.length === 0)
      return { exported: 0, failed, wrote: false };
    let webview = null;
    try {
      webview = await prepareExportWebview(host, {
        bodyHtml: buildCombinedExportBody(gridHtmls),
        bodyClass
      });
      const bytes = await printPreparedWebview(webview);
      await this.app.vault.adapter.writeBinary(
        resolveCombinedOutputPath(this.combinedFolder, this.combinedName),
        bytes
      );
      return { exported: gridHtmls.length, failed, wrote: true };
    } finally {
      webview == null ? void 0 : webview.remove();
    }
  }
  /** Notice + close policy shared by both modes: a clean run closes the modal;
   *  any failure (or nothing written) keeps it open so the user can retry. */
  reportExport(total, summary) {
    var _a;
    const { exported, failed, wrote } = summary;
    if (!wrote) {
      new import_obsidian2.Notice("Nothing exported \u2014 no notes could be rendered.");
    } else if (failed.length === 0) {
      const what = this.outputMode === "combined" ? `combined PDF (${exported} note${exported === 1 ? "" : "s"})` : exported === 1 ? "1 PDF" : `${exported} PDFs`;
      new import_obsidian2.Notice(`Exported ${what}.`);
      this.close();
      return;
    } else {
      new import_obsidian2.Notice(
        `Exported ${exported} of ${total}. Failed: ${failed.join(", ")}.`
      );
    }
    (_a = this.exportBtn) == null ? void 0 : _a.setButtonText("Export");
    this.updateButtons();
  }
  /** Size the body-level capture host to the in-modal preview surface. */
  positionCaptureHost() {
    if (!this.captureHost || !this.previewEl)
      return;
    const r = this.previewEl.getBoundingClientRect();
    this.captureHost.style.left = `${r.left}px`;
    this.captureHost.style.top = `${r.top}px`;
    this.captureHost.style.width = `${r.width}px`;
    this.captureHost.style.height = `${r.height}px`;
  }
  onClose() {
    var _a;
    this.disposePreview();
    (_a = this.captureHost) == null ? void 0 : _a.remove();
    this.contentEl.empty();
    this.previewEl = null;
    this.captureHost = null;
    this.renderBtn = null;
    this.exportBtn = null;
  }
};

// livePreview.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var INVALID_CALLOUT_CLASS = "cornell-invalid";
var TITLE_OVER_LIMIT_CLASS = "cornell-title-over-limit";
var cornellRefreshEffect = import_state.StateEffect.define();
function buildCornellEditorExtension(ctx) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.rebuildTimer = null;
        this.decorations = this.build(view);
        this.embedObserver = new MutationObserver((records) => {
          const touched = /* @__PURE__ */ new Set();
          for (const record of records) {
            const target = record.target;
            if (target.instanceOf(HTMLElement)) {
              const host = target.closest(".cm-embed-block");
              if (host)
                touched.add(host);
            }
            record.addedNodes.forEach((node) => {
              if (!node.instanceOf(HTMLElement))
                return;
              if (node.matches(".cm-embed-block"))
                touched.add(node);
              node.querySelectorAll(".cm-embed-block").forEach((block) => touched.add(block));
            });
          }
          touched.forEach(stampEmbedBlock);
        });
        this.embedObserver.observe(view.dom, {
          childList: true,
          subtree: true
        });
        view.dom.querySelectorAll(".cm-embed-block").forEach(stampEmbedBlock);
      }
      update(update) {
        for (const tr of update.transactions) {
          for (const effect of tr.effects) {
            if (effect.is(cornellRefreshEffect)) {
              this.cancelPendingRebuild();
              this.decorations = this.build(update.view);
              return;
            }
          }
        }
        if (update.docChanged) {
          this.scheduleRebuild(update.view);
        }
      }
      scheduleRebuild(view) {
        this.cancelPendingRebuild();
        this.rebuildTimer = window.setTimeout(() => {
          this.rebuildTimer = null;
          view.dispatch({ effects: cornellRefreshEffect.of() });
        }, 300);
      }
      cancelPendingRebuild() {
        if (this.rebuildTimer !== null) {
          window.clearTimeout(this.rebuildTimer);
          this.rebuildTimer = null;
        }
      }
      destroy() {
        this.cancelPendingRebuild();
        this.embedObserver.disconnect();
      }
      build(view) {
        var _a;
        const file = findFileForEditor(view, ctx.app);
        if (!file)
          return import_view.Decoration.none;
        const cache = ctx.app.metadataCache.getFileCache(file);
        if (!hasCornellCssClass(cache == null ? void 0 : cache.frontmatter))
          return import_view.Decoration.none;
        const text = view.state.doc.toString();
        const slots = classifyBlocks(text, cache == null ? void 0 : cache.frontmatter);
        const ranges = [];
        const lineDeco = (attrs) => import_view.Decoration.line({ attributes: attrs });
        for (const slot of slots) {
          if (slot.role === "cue" || slot.role === "summary" || slot.role === "title") {
            const attrs = { [ATTR_LINE]: slot.role };
            if (slot.role === "title" && titleExceedsLimit((_a = slot.content) != null ? _a : "")) {
              attrs[ATTR_OVER_LIMIT] = "";
            }
            const startLineNum = view.state.doc.lineAt(slot.sourceRange.from).number;
            const endLineNum = view.state.doc.lineAt(
              Math.max(slot.sourceRange.from, slot.sourceRange.to - 1)
            ).number;
            for (let n = startLineNum; n <= endLineNum; n++) {
              const line = view.state.doc.line(n);
              ranges.push(lineDeco(attrs).range(line.from));
            }
            if (slot.role === "summary") {
              const firstLine = view.state.doc.line(startLineNum);
              ranges.push(
                lineDeco({ [ATTR_SUMMARY_START]: "" }).range(firstLine.from)
              );
            }
          } else if (slot.role === "body") {
            for (const r of slot.lineRanges) {
              ranges.push(
                lineDeco({ [ATTR_LINE]: "body" }).range(
                  view.state.doc.lineAt(r.from).from
                )
              );
            }
          } else if (slot.role === "gap") {
            for (const r of slot.lineRanges) {
              ranges.push(
                lineDeco({ [ATTR_LINE]: "gap" }).range(
                  view.state.doc.lineAt(r.from).from
                )
              );
            }
          } else if (slot.role === "full" && slot.isHeading && slot.cueGroup != null) {
            for (const r of slot.lineRanges) {
              ranges.push(
                lineDeco({ [ATTR_LINE]: "heading" }).range(
                  view.state.doc.lineAt(r.from).from
                )
              );
            }
          }
        }
        ranges.sort((a, b) => a.from - b.from);
        const invalidReasons = slots.filter((s) => s.role === "cue").map((s) => {
          var _a2;
          return (_a2 = s.invalid) != null ? _a2 : null;
        });
        const titleOverFlags = slots.filter((s) => s.role === "title").map((s) => {
          var _a2;
          return titleExceedsLimit((_a2 = s.content) != null ? _a2 : "");
        });
        window.requestAnimationFrame(() => {
          markInvalidCueCallouts(view, invalidReasons);
          markOverLimitTitles(view, titleOverFlags);
        });
        return import_view.Decoration.set(ranges, true);
      }
    },
    {
      decorations: (v) => v.decorations
    }
  );
}
function resolveExpansion(lineText, rules) {
  for (const rule of rules) {
    if (rule.trigger && lineText === rule.trigger)
      return rule.insert;
  }
  return null;
}
function buildCalloutExpander(ctx) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(_view) {
      }
      update(update) {
        if (!update.docChanged)
          return;
        const rules = ctx.getRules();
        if (!rules.some((r) => r.trigger))
          return;
        const view = update.view;
        const file = findFileForEditor(view, ctx.app);
        if (!file)
          return;
        const cache = ctx.app.metadataCache.getFileCache(file);
        if (!hasCornellCssClass(cache == null ? void 0 : cache.frontmatter))
          return;
        const sel = view.state.selection.main;
        if (!sel.empty)
          return;
        const line = view.state.doc.lineAt(sel.head);
        if (sel.head !== line.to)
          return;
        const insert = resolveExpansion(line.text, rules);
        if (insert === null)
          return;
        const from = line.from;
        const expected = line.text;
        queueMicrotask(() => {
          if (from > view.state.doc.length)
            return;
          const ln = view.state.doc.lineAt(from);
          if (ln.from !== from || ln.text !== expected)
            return;
          view.dispatch({
            changes: { from: ln.from, to: ln.to, insert },
            selection: { anchor: ln.from + insert.length }
          });
        });
      }
    }
  );
}
function stampEmbedBlock(block) {
  const has = (type2) => block.querySelector(`.callout[data-callout="${type2}"]`) !== null;
  const type = has("cue") ? "cue" : has("summary") ? "summary" : has("title") ? "title" : null;
  if (type) {
    block.setAttribute(ATTR_SLOT, type);
  } else {
    block.removeAttribute(ATTR_SLOT);
  }
  block.toggleAttribute(
    ATTR_INVALID,
    block.querySelector(
      `.callout[data-callout="cue"].${INVALID_CALLOUT_CLASS}`
    ) !== null
  );
}
function markInvalidCueCallouts(view, reasons) {
  const cueEls = view.dom.querySelectorAll(
    '.callout[data-callout="cue"]'
  );
  cueEls.forEach((el, idx) => {
    var _a;
    const reason = (_a = reasons[idx]) != null ? _a : null;
    el.classList.toggle(INVALID_CALLOUT_CLASS, reason !== null);
    const wrapper = el.closest(".cm-embed-block");
    if (wrapper) {
      wrapper.toggleAttribute(ATTR_INVALID, reason !== null);
    }
    if (reason) {
      el.setAttribute("title", invalidTooltip(reason));
    } else {
      el.removeAttribute("title");
    }
  });
}
function markOverLimitTitles(view, overFlags) {
  const titleEls = view.dom.querySelectorAll(
    '.callout[data-callout="title"]'
  );
  titleEls.forEach((el, idx) => {
    var _a;
    const over = (_a = overFlags[idx]) != null ? _a : false;
    el.classList.toggle(TITLE_OVER_LIMIT_CLASS, over);
    if (over) {
      el.setAttribute("title", TITLE_OVER_LIMIT_TOOLTIP);
    } else {
      el.removeAttribute("title");
    }
  });
}
function findFileForEditor(view, app) {
  var _a;
  const dom = view.dom;
  for (const leaf of app.workspace.getLeavesOfType("markdown")) {
    const v = leaf.view;
    if (v.containerEl.contains(dom)) {
      return (_a = v.file) != null ? _a : null;
    }
  }
  return null;
}

// reviewMode.ts
var import_obsidian3 = require("obsidian");

// reviewModel.ts
function isRevealTrigger(role) {
  return role === "cue" || role === "summary";
}
var ReviewState = class {
  constructor() {
    this.active = false;
    /** Per-file set of currently-revealed group keys, kept so reveals survive
     *  Reading-view re-renders (the controller re-applies them per wrapper). */
    this.revealed = /* @__PURE__ */ new Map();
  }
  isActive() {
    return this.active;
  }
  /** Flip review mode and return the new state. Turning OFF clears every
   *  reveal, so the next time the mode turns on the note starts fully
   *  blurred — a fresh recall session. */
  toggle() {
    this.active = !this.active;
    if (!this.active)
      this.revealed.clear();
    return this.active;
  }
  /** Re-blur everything without leaving review mode (the "reset" command). */
  reset() {
    this.revealed.clear();
  }
  isRevealed(filePath, group) {
    var _a, _b;
    return (_b = (_a = this.revealed.get(filePath)) == null ? void 0 : _a.has(group)) != null ? _b : false;
  }
  /** Record a reveal (or re-hide) of one group in one file. Groups toggle
   *  independently; files never share reveals. */
  setRevealed(filePath, group, revealed) {
    var _a;
    const set = (_a = this.revealed.get(filePath)) != null ? _a : /* @__PURE__ */ new Set();
    if (revealed)
      set.add(group);
    else
      set.delete(group);
    this.revealed.set(filePath, set);
  }
};

// reviewMode.ts
var REVIEW_CLASS = "cornell-review";
var ReviewModeController = class {
  constructor(app) {
    this.app = app;
    this.state = new ReviewState();
  }
  isActive() {
    return this.state.isActive();
  }
  /** Flip review mode and apply it to every open Reading view immediately.
   *  Turning it OFF resets all reveals (the model clears its memory; the
   *  stamped attributes are cleared here), so the next time it's turned on the
   *  note starts fully blurred. When turning it ON from a non-Reading view,
   *  the notice hints that review mode is only visible in Reading view. */
  toggle() {
    const active = this.state.toggle();
    if (!active)
      this.clearRevealAttributes();
    this.applyToAllSizers();
    if (!active) {
      new import_obsidian3.Notice("Review mode off");
    } else if (this.inReadingView()) {
      new import_obsidian3.Notice("Review mode on");
    } else {
      new import_obsidian3.Notice("Review mode on \u2014 switch to reading view to use it");
    }
  }
  inReadingView() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    return !!view && view.getMode() === "preview";
  }
  /** Re-blur everything without leaving review mode (the "reset" command). */
  resetReveals() {
    this.state.reset();
    this.clearRevealAttributes();
  }
  /** Re-apply a persisted reveal to a wrapper the post-processor just
   *  (re-)stamped, so revealed regions survive Reading-view re-renders (edits,
   *  returning to the note). Keyed by the wrapper's group: the attribute is
   *  added when the model has that group revealed for the file, removed
   *  otherwise. A no-op for wrappers with no group key. */
  restoreWrapper(wrapper, filePath) {
    const group = wrapper.getAttribute(ATTR_CUE_GROUP);
    if (!group)
      return;
    if (this.state.isRevealed(filePath, group)) {
      wrapper.setAttribute(ATTR_REVEALED, "");
    } else {
      wrapper.removeAttribute(ATTR_REVEALED);
    }
  }
  /** Handle a click anywhere in the workspace. When review mode is active and
   *  the click landed on a cue or summary inside a review sizer, toggle the
   *  reveal of that wrapper's group — for a cue that reveals/hides its whole
   *  notes region; for a summary, just itself. Reveals accumulate (each group
   *  toggles independently). A no-op otherwise, so normal clicks are untouched. */
  handleClick(evt) {
    if (!this.state.isActive() || evt.button !== 0)
      return;
    const target = evt.target;
    if (!target)
      return;
    const sizer = target.closest(`.markdown-preview-sizer.${REVIEW_CLASS}`);
    if (!sizer)
      return;
    const wrapper = target.closest(`[${ATTR_CUE_GROUP}]`);
    if (!wrapper || !sizer.contains(wrapper))
      return;
    if (!isRevealTrigger(wrapper.getAttribute(ATTR_SLOT)))
      return;
    const group = wrapper.getAttribute(ATTR_CUE_GROUP);
    if (!group)
      return;
    this.toggleGroup(sizer, group);
  }
  /** Reflect the current state onto a sizer the post-processor just rendered,
   *  so a freshly opened Cornell note matches review mode without a re-toggle.
   *  Idempotent across the per-block post-processor calls. */
  syncSizer(sizer) {
    sizer.classList.toggle(REVIEW_CLASS, this.state.isActive());
  }
  applyToAllSizers() {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const view = leaf.view;
      view.containerEl.querySelectorAll(".markdown-preview-sizer").forEach(
        (sizer) => sizer.classList.toggle(REVIEW_CLASS, this.state.isActive())
      );
    });
  }
  /** Reveal or hide every wrapper in `sizer` carrying `group`. The new state is
   *  the inverse of whether the group is currently revealed in THIS view (read
   *  from the DOM, so a single click flips the whole group together), and the
   *  choice is recorded in the model for later re-application. */
  toggleGroup(sizer, group) {
    const selector = `[${ATTR_CUE_GROUP}="${group}"]`;
    const willReveal = !sizer.querySelector(`${selector}[${ATTR_REVEALED}]`);
    sizer.querySelectorAll(selector).forEach((w) => {
      if (willReveal)
        w.setAttribute(ATTR_REVEALED, "");
      else
        w.removeAttribute(ATTR_REVEALED);
    });
    const filePath = this.filePathForSizer(sizer);
    if (!filePath)
      return;
    this.state.setRevealed(filePath, group, willReveal);
  }
  filePathForSizer(sizer) {
    var _a, _b;
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view.containerEl.contains(sizer))
        return (_b = (_a = view.file) == null ? void 0 : _a.path) != null ? _b : null;
    }
    return null;
  }
  /** Strip the revealed attribute from every open view — the DOM half of a
   *  reveal reset; the model half is `state.reset()` / the off-toggle clear. */
  clearRevealAttributes() {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const view = leaf.view;
      view.containerEl.querySelectorAll(`[${ATTR_REVEALED}]`).forEach((el) => el.removeAttribute(ATTR_REVEALED));
    });
  }
};

// settings.ts
var import_obsidian4 = require("obsidian");
var DEFAULT_SETTINGS = {
  cueWidth: 120,
  dividerColor: "lightgrey",
  dividerThickness: 1,
  cueShortcut: "",
  summaryShortcut: "",
  titleShortcut: "",
  reviewHoverHighlight: false,
  pdfExportEnabled: false
};
function findDuplicateTrigger(triggers) {
  const seen = /* @__PURE__ */ new Set();
  for (const raw of [triggers.cue, triggers.summary, triggers.title]) {
    const t = raw.trim();
    if (!t)
      continue;
    if (seen.has(t))
      return t;
    seen.add(t);
  }
  return null;
}
var CornellSettingsTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    /** Which sub-tab is showing. Persisted only for the lifetime of the open
     *  settings pane — it resets to "layout" each time the pane is reopened. */
    this.activeTab = "layout";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const nav = containerEl.createDiv({ cls: "cornell-settings-nav" });
    const body = containerEl.createDiv({ cls: "cornell-settings-body" });
    const tabs = [
      { id: "layout", label: "Layout" },
      { id: "optional", label: "Optional" }
    ];
    const renderBody = () => {
      body.empty();
      if (this.activeTab === "layout")
        this.renderLayoutTab(body);
      else
        this.renderOptionalTab(body);
    };
    tabs.forEach(({ id, label }) => {
      const btn = nav.createEl("button", {
        text: label,
        cls: "cornell-settings-tab"
      });
      btn.toggleClass("is-active", this.activeTab === id);
      btn.addEventListener("click", () => {
        this.activeTab = id;
        nav.querySelectorAll(".cornell-settings-tab").forEach((el) => el.removeClass("is-active"));
        btn.addClass("is-active");
        renderBody();
      });
    });
    renderBody();
  }
  /** Core layout knobs — the everyday Cornell-sheet geometry. */
  renderLayoutTab(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Cue column width").setDesc("Width of the left margin column for cues, in pixels.").addText(
      (text) => text.setPlaceholder(String(DEFAULT_SETTINGS.cueWidth)).setValue(String(this.plugin.settings.cueWidth)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (Number.isFinite(n) && n > 0) {
          this.plugin.settings.cueWidth = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Divider line color").setDesc(
      "Color of the vertical line between the cue column and the notes body. Any CSS color value works, such as lightgrey, #ccc, or rgb(180, 180, 180)."
    ).addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.dividerColor).setValue(this.plugin.settings.dividerColor).onChange(async (value) => {
        this.plugin.settings.dividerColor = value || DEFAULT_SETTINGS.dividerColor;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Divider line thickness").setDesc("Thickness of the divider line, in pixels. Set to 0 to hide it.").addText(
      (text) => text.setPlaceholder(String(DEFAULT_SETTINGS.dividerThickness)).setValue(String(this.plugin.settings.dividerThickness)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (Number.isFinite(n) && n >= 0) {
          this.plugin.settings.dividerThickness = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
  /** Opt-in extras — features that not every user needs, kept out of the way so
   *  the main pane stays uncluttered. */
  renderOptionalTab(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Enable PDF export").setDesc(
      "Show a PDF export option in the right-click menu, off by default. Cornell notes and folders of them can then be exported as study sheets."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.pdfExportEnabled).onChange(async (value) => {
        this.plugin.settings.pdfExportEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Highlight cue on hover (review mode)").setDesc(
      "In review mode, draw a colored box around a cue (and the summary) when you hover it, marking it as clickable. Off by default."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.reviewHoverHighlight).onChange(async (value) => {
        this.plugin.settings.reviewHoverHighlight = value;
        await this.plugin.saveSettings();
      })
    );
    this.addShortcutSetting(containerEl, {
      key: "cue",
      name: "Cue shortcut",
      desc: "Type this word on its own line in a Cornell note and it auto-expands into '> [!cue] ', dropping the cursor right after it. Leave blank to disable (you can always type '> [!cue]' by hand). Must differ from the summary and title shortcuts. Example: cc",
      placeholder: "e.g. cc"
    });
    this.addShortcutSetting(containerEl, {
      key: "summary",
      name: "Summary shortcut",
      desc: "Type this word on its own line in a Cornell note and it auto-expands into '> [!summary] ', dropping the cursor right after it. Leave blank to disable (you can always type '> [!summary]' by hand). Must differ from the cue and title shortcuts. Example: ss",
      placeholder: "e.g. ss"
    });
    this.addShortcutSetting(containerEl, {
      key: "title",
      name: "Title shortcut",
      desc: "Type this word on its own line in a Cornell note and it auto-expands into '> [!title] ', dropping the cursor right after it. Leave blank to disable (you can always type '> [!title]' by hand). Must differ from the cue and summary shortcuts. Example: tt",
      placeholder: "e.g. tt"
    });
  }
  /** Live snapshot of all three shortcut triggers from saved settings. */
  currentTriggers() {
    return {
      cue: this.plugin.settings.cueShortcut,
      summary: this.plugin.settings.summaryShortcut,
      title: this.plugin.settings.titleShortcut
    };
  }
  /** Render one shortcut text setting. All three route through here so the
   *  distinct-trigger check applies uniformly: a value that collides with
   *  another non-empty shortcut is rejected (error notice + field reverts to
   *  the last saved value); a blank value always disables that shortcut. */
  addShortcutSetting(containerEl, opts) {
    const settingKey = `${opts.key}Shortcut`;
    new import_obsidian4.Setting(containerEl).setName(opts.name).setDesc(opts.desc).addText(
      (text) => text.setPlaceholder(opts.placeholder).setValue(this.plugin.settings[settingKey]).onChange(async (value) => {
        const candidate = value.trim();
        const triggers = this.currentTriggers();
        triggers[opts.key] = candidate;
        if (candidate && findDuplicateTrigger(triggers) === candidate) {
          new import_obsidian4.Notice(
            `Shortcut "${candidate}" is already used by another shortcut. Pick a different word.`
          );
          text.setValue(this.plugin.settings[settingKey]);
          return;
        }
        this.plugin.settings[settingKey] = candidate;
        await this.plugin.saveSettings();
      })
    );
  }
};

// main.ts
var CSS_VAR_CUE_WIDTH = "--cue-width";
var CSS_VAR_LINE_COLOR = "--cue-line-color";
var CSS_VAR_LINE_THICKNESS = "--cue-line-thickness";
var CLASS_REVIEW_HOVER_BOX = "cornell-review-hover-box";
var CORNELL_TEMPLATE = `---
cssclasses:
  - cornell-note
---

> [!cue] Topic 1
## Topic 1

Body notes for topic 1 go here. Write freely \u2014 paragraphs, lists, code, anything.

> [!cue] Topic 2
- Bullet point
- Another bullet point

> [!cue] Topic 3
## Topic 3

More notes...

> [!summary]
> Write your summary here.
`;
function cornellHost(el) {
  var _a, _b, _c;
  const sizer = el.closest(".markdown-preview-sizer");
  if (sizer)
    return sizer;
  const CONTAINER = ".markdown-rendered, .markdown-preview-view, .print";
  const scope = (_c = (_b = el.closest(CONTAINER)) != null ? _b : (_a = el.ownerDocument) == null ? void 0 : _a.querySelector(CONTAINER)) != null ? _c : el;
  const anchor = scope.querySelector(
    '.callout[data-callout="cue"], .callout[data-callout="title"], .callout[data-callout="summary"]'
  );
  if (!anchor)
    return null;
  let block = anchor;
  while (block.parentElement && block.parentElement !== scope) {
    block = block.parentElement;
  }
  return block.parentElement === scope ? scope : block.parentElement;
}
function applyAttributes(el, attrs) {
  for (const [name, value] of Object.entries(attrs)) {
    if (value === null) {
      el.removeAttribute(name);
    } else {
      el.setAttribute(name, value);
    }
  }
}
function hostChild(el, host) {
  let e = el;
  while (e && e.parentElement && e.parentElement !== host) {
    e = e.parentElement;
  }
  return e && e.parentElement === host ? e : null;
}
var CornellNotesPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    await this.loadSettings();
    this.applyCssVariables();
    this.reviewMode = new ReviewModeController(this.app);
    this.addSettingTab(new CornellSettingsTab(this.app, this));
    this.addCommand({
      id: "create-cornell-note",
      name: "Create new note",
      callback: () => this.createCornellNote()
    });
    this.addCommand({
      id: "toggle-review-mode",
      name: "Toggle review mode",
      callback: () => this.reviewMode.toggle()
    });
    this.addCommand({
      id: "reset-review-reveals",
      name: "Reset review reveals (re-blur all)",
      callback: () => this.reviewMode.resetReveals()
    });
    this.registerDomEvent(
      activeDocument,
      "click",
      (evt) => this.reviewMode.handleClick(evt)
    );
    this.addRibbonIcon(
      "columns-3",
      "Create new note",
      () => this.createCornellNote()
    );
    this.registerEditorExtension([
      buildCornellEditorExtension({ app: this.app }),
      buildCalloutExpander({
        app: this.app,
        // Ordered rules; earlier wins on identical triggers. Cue is listed
        // first, so if the user sets the same word for both, the cue takes it.
        getRules: () => [
          { trigger: this.settings.cueShortcut.trim(), insert: "> [!cue] " },
          {
            trigger: this.settings.summaryShortcut.trim(),
            insert: "> [!summary] "
          },
          {
            trigger: this.settings.titleShortcut.trim(),
            insert: "> [!title] "
          }
        ]
      })
    ]);
    this.registerMarkdownPostProcessor(async (el, ctx) => {
      var _a, _b, _c;
      const file = this.app.vault.getAbstractFileByPath(ctx.sourcePath);
      if (!(file instanceof import_obsidian5.TFile))
        return;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!hasCornellCssClass(cache == null ? void 0 : cache.frontmatter))
        return;
      const source = await this.app.vault.cachedRead(file);
      const host = cornellHost(el);
      if (host) {
        host.classList.add("cornell-grid");
        host.classList.toggle(
          "cornell-leading-title",
          leadsWithTitle(source, cache == null ? void 0 : cache.frontmatter)
        );
        this.reviewMode.syncSizer(host);
      }
      const info = ctx.getSectionInfo(el);
      if (!info) {
        if (host)
          stampExportHost(host);
        return;
      }
      const resolved = classifySection(
        source,
        cache == null ? void 0 : cache.frontmatter,
        info.lineStart,
        info.lineEnd
      );
      if (!resolved)
        return;
      const { slot, notesEnd } = resolved;
      const wrapper = (_a = host ? hostChild(el, host) : null) != null ? _a : el;
      applyAttributes(wrapper, slotAttributes(slot, notesEnd));
      this.reviewMode.restoreWrapper(wrapper, ctx.sourcePath);
      if (slot.role === "cue") {
        const cueEl = el.querySelector(
          '.callout[data-callout="cue"]'
        );
        if (cueEl) {
          const reason = (_b = slot.invalid) != null ? _b : null;
          cueEl.classList.toggle("cornell-invalid", reason !== null);
          if (reason) {
            cueEl.setAttribute("title", invalidTooltip(reason));
          } else {
            cueEl.removeAttribute("title");
          }
        }
      }
      if (slot.role === "title") {
        const titleEl = el.querySelector(
          '.callout[data-callout="title"]'
        );
        if (titleEl) {
          const over = titleExceedsLimit((_c = slot.content) != null ? _c : "");
          titleEl.classList.toggle("cornell-title-over-limit", over);
          if (over) {
            titleEl.setAttribute("title", TITLE_OVER_LIMIT_TOOLTIP);
          } else {
            titleEl.removeAttribute("title");
          }
        }
      }
    });
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        this.refreshForFile(file);
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (import_obsidian5.Platform.isMobile)
          return;
        if (!this.settings.pdfExportEnabled)
          return;
        const getFrontmatter = (f) => {
          var _a;
          return (_a = this.app.metadataCache.getFileCache(f)) == null ? void 0 : _a.frontmatter;
        };
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          if (!hasCornellCssClass(getFrontmatter(file)))
            return;
          menu.addItem(
            (item) => item.setTitle("Export PDF").setIcon("file-text").onClick(
              () => new CornellPdfExportModal(this, [file]).open()
            )
          );
          return;
        }
        if (file instanceof import_obsidian5.TFolder) {
          const notes = collectCornellNotes(
            descendantMarkdownFiles(file),
            getFrontmatter
          );
          if (notes.length === 0)
            return;
          menu.addItem(
            (item) => item.setTitle("Export to PDF").setIcon("file-text").onClick(() => new CornellPdfExportModal(this, notes).open())
          );
        }
      })
    );
  }
  onunload() {
    const r = activeDocument.documentElement;
    r.style.removeProperty(CSS_VAR_CUE_WIDTH);
    r.style.removeProperty(CSS_VAR_LINE_COLOR);
    r.style.removeProperty(CSS_VAR_LINE_THICKNESS);
    r.classList.remove(CLASS_REVIEW_HOVER_BOX);
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyCssVariables();
    this.dispatchRefreshToAllEditors();
  }
  applyCssVariables() {
    const r = activeDocument.documentElement;
    r.style.setProperty(CSS_VAR_CUE_WIDTH, `${this.settings.cueWidth}px`);
    r.style.setProperty(CSS_VAR_LINE_COLOR, this.settings.dividerColor);
    r.style.setProperty(
      CSS_VAR_LINE_THICKNESS,
      `${this.settings.dividerThickness}px`
    );
    r.classList.toggle(
      CLASS_REVIEW_HOVER_BOX,
      this.settings.reviewHoverHighlight
    );
  }
  dispatchRefreshToAllEditors() {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const view = leaf.view;
      const cm = view.editor.cm;
      if (cm) {
        cm.dispatch({ effects: cornellRefreshEffect.of() });
      }
    });
  }
  refreshForFile(file) {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      var _a;
      const view = leaf.view;
      if (!view || ((_a = view.file) == null ? void 0 : _a.path) !== file.path)
        return;
      const cm = view.editor.cm;
      if (cm) {
        cm.dispatch({ effects: cornellRefreshEffect.of() });
      }
    });
  }
  async createCornellNote() {
    const folder = this.targetFolder();
    const path = await this.uniqueChildPath(folder, "Untitled Cornell note");
    try {
      const file = await this.app.vault.create(path, CORNELL_TEMPLATE);
      await this.app.workspace.getLeaf(false).openFile(file);
    } catch (e) {
      new import_obsidian5.Notice(`Could not create Cornell note: ${String(e)}`);
    }
  }
  targetFolder() {
    const active = this.app.workspace.getActiveFile();
    const parent = active == null ? void 0 : active.parent;
    if (parent instanceof import_obsidian5.TFolder)
      return parent;
    return this.app.vault.getRoot();
  }
  async uniqueChildPath(folder, baseName) {
    const prefix = folder.isRoot() ? "" : `${folder.path}/`;
    let candidate = `${prefix}${baseName}.md`;
    if (!await this.app.vault.adapter.exists(candidate))
      return candidate;
    for (let n = 1; n < 1e3; n++) {
      candidate = `${prefix}${baseName} ${n}.md`;
      if (!await this.app.vault.adapter.exists(candidate))
        return candidate;
    }
    return `${prefix}${baseName} ${Date.now()}.md`;
  }
};

/* nosourcemap */